name: News Update

on:
  schedule:
    - cron: '0 * * * *'  # Запускається раз на годину
  workflow_dispatch:  # Дозволяє запуск вручну

jobs:
  update_news:
    runs-on: ubuntu-latest

    steps:
      - name: Клонування репозиторію
        uses: actions/checkout@v2

      - name: Виконання API-запиту (тимчасово в новий файл)
        run: |
          curl -s "https://gnews.io/api/v4/top-headlines?category=general&lang=uk&country=uk&max=10&apikey=${{ secrets.GNEWS_API_KEY }}" -o new_news.json
      
      - name: Перевірка, чи є нові дані
        run: |
          if cmp -s new_news.json news.json; then
            echo "No new updates, skipping commit."
            exit 0
          fi
          mv new_news.json news.json

      - name: Налаштування Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Коміт змін та пуш
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add news.json
          git commit -m "Автоматичне оновлення новин"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
