name: News Update

on:
  schedule:
    - cron: '0 * * * *'  # Запускається раз на годину
  workflow_dispatch:  # Дозволяє запуск вручну

jobs:
  update_news:
    runs-on: ubuntu-latest

    steps:
      - name: Клонування репозиторію
        uses: actions/checkout@v2

      - name: Виконання API-запиту
        run: |
          curl -s "https://gnews.io/api/v4/top-headlines?category=ukraine&lang=en&country=uk&max=2&apikey=${{ secrets.GNEWS_API_KEY }}" -o news.json
      
      - name: Налаштування Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Перевірка змін у news.json
        run: |
          if git diff --exit-code news.json; then
            echo "No changes detected, skipping commit."
            exit 0
          fi

      - name: Коміт змін та пуш
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add news.json
          git commit -m "Автоматичне оновлення новин"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
